{% set conda_prefix = os.environ.get('CONDA_PREFIX') %}
name: lightning

channels:
  - conda-forge
  - defaults
dependencies:
  - doxygen
  - eigen
  - clang-format=13.0.1
  - cmake=3.22.1
  - pip=21.2.4
  - python=3.9.7
  - sdl2=2.0.18
  - sdl2_image=2.0.5
  - gcc  # [linux]
  - pip
  - invoke
  - catch2
  - cppcheck
  - pytest
  - pytest-regressions
  - clang-format
  - ninja
  - pillow
  - numpy
  - pytest-cpp
  - pytest-xdist
  - pip:
    - pre-commit

environment:
  LIGHTNING_ROOT: {{ root }}
  LIGHTNING_GRAPHICS: {{ root }}/graphics
  LIGHTNING_CORE: {{ root }}/core
  LIGHTNING_BUILD_DIR: {{ root }}/build
  LIGHTNING_BIN_DIR: {{ root }}/build/install/bin
  LIGHTNING_TESTS: {{ root }}/tests
