name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Setup Miniconda
      # You may pin to the exact commit or the version.
      # uses: conda-incubator/setup-miniconda@35d1405e78aa3f784fe3ce9a2eb378d5eeb62169
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        auto-activate-base: true
        # Conda configuration. Comma separated list of channels to use in order of priority. See https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/ for more information.
        channels: conda-forge
        auto-update-conda: true
        python-version: '3.9'
    - name: Conda info
      shell: bash -l {0}
      run: conda info
    - name: Conda list
      shell: pwsh
      run: conda list
    - name: Environment
      shell: bash -l {0}
      run: printenv | sort
    - name: Install dependencies
      run: |
        conda install conda-devenv -c conda-forge
        conda install mamba -c conda-forge  
        conda devenv
        
    - name: Compile
      run: |
        conda activate lightning
        inv build
        
